- apt:
    name: "{{ item }}"
    state: present
  loop:
    - git
- name: Download docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.28.5/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '0755'
- name: Checkout repository
  ansible.builtin.git:
    repo: https://github.com/plansoft-it/docker-course-samples-and-execises.git
    dest: /home/corso/docker-course-samples-and-execises
- name: Adjust permission
  ansible.builtin.file:
    path: /home/corso/docker-course-samples-and-execises
    owner: corso
    group: corso
    recurse: yes

